// +build !ignore_autogenerated

// Copyright 2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKE) DeepCopyInto(out *TestClusterGKE) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKE.
func (in *TestClusterGKE) DeepCopy() *TestClusterGKE {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestClusterGKE) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKECondition) DeepCopyInto(out *TestClusterGKECondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKECondition.
func (in *TestClusterGKECondition) DeepCopy() *TestClusterGKECondition {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKECondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TestClusterGKEConditions) DeepCopyInto(out *TestClusterGKEConditions) {
	{
		in := &in
		*out = make(TestClusterGKEConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKEConditions.
func (in TestClusterGKEConditions) DeepCopy() TestClusterGKEConditions {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKEConditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKEJobRunnerSpec) DeepCopyInto(out *TestClusterGKEJobRunnerSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InitImage != nil {
		in, out := &in.InitImage, &out.InitImage
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKEJobRunnerSpec.
func (in *TestClusterGKEJobRunnerSpec) DeepCopy() *TestClusterGKEJobRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKEJobRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKEJobSpec) DeepCopyInto(out *TestClusterGKEJobSpec) {
	*out = *in
	if in.Runner != nil {
		in, out := &in.Runner, &out.Runner
		*out = new(TestClusterGKEJobRunnerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagesToTest != nil {
		in, out := &in.ImagesToTest, &out.ImagesToTest
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKEJobSpec.
func (in *TestClusterGKEJobSpec) DeepCopy() *TestClusterGKEJobSpec {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKEJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKEList) DeepCopyInto(out *TestClusterGKEList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestClusterGKE, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKEList.
func (in *TestClusterGKEList) DeepCopy() *TestClusterGKEList {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKEList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestClusterGKEList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKESpec) DeepCopyInto(out *TestClusterGKESpec) {
	*out = *in
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ConfigTemplate != nil {
		in, out := &in.ConfigTemplate, &out.ConfigTemplate
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.KubernetesVersion != nil {
		in, out := &in.KubernetesVersion, &out.KubernetesVersion
		*out = new(string)
		**out = **in
	}
	if in.JobSpec != nil {
		in, out := &in.JobSpec, &out.JobSpec
		*out = new(TestClusterGKEJobSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKESpec.
func (in *TestClusterGKESpec) DeepCopy() *TestClusterGKESpec {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKEStatus) DeepCopyInto(out *TestClusterGKEStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(TestClusterGKEConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make(map[string]TestClusterGKEConditions, len(*in))
		for key, val := range *in {
			var outVal []TestClusterGKECondition
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(TestClusterGKEConditions, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKEStatus.
func (in *TestClusterGKEStatus) DeepCopy() *TestClusterGKEStatus {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKEStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestClusterGKE_WithoutTypeMeta) DeepCopyInto(out *TestClusterGKE_WithoutTypeMeta) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestClusterGKE_WithoutTypeMeta.
func (in *TestClusterGKE_WithoutTypeMeta) DeepCopy() *TestClusterGKE_WithoutTypeMeta {
	if in == nil {
		return nil
	}
	out := new(TestClusterGKE_WithoutTypeMeta)
	in.DeepCopyInto(out)
	return out
}
