
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: gke-test-cluster-operator
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clusters.ci.cilium.io
  resources:
  - testclustergkes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.ci.cilium.io
  resources:
  - testclustergkes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clusters.ci.cilium.io
  resources:
  - testclusterpoolgkes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.ci.cilium.io
  resources:
  - testclusterpoolgkes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - computenetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - computenetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - computesubnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - computesubnetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containerclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containernodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containernodepools/status
  verbs:
  - get
  - patch
  - update
