name: CI
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: ['**']

jobs:
  build-image:
    name: Build new images locally
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for imagine to detect -dev suffix
      - uses: docker://quay.io/cilium/image-maker:68cf0628c7a77124319cb8c33434b8cdb42a3865
        name: Run make lint
        with:
          entrypoint: make
          args: lint
      - uses: docker://quay.io/cilium/image-maker:68cf0628c7a77124319cb8c33434b8cdb42a3865
        name: Build all images and generate manifests
        env:
          DOCKER_HUB_PUBLIC_ACCESS_ONLY: "true"
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME_GKE_TEST_CLUSTER_OPERATOR }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD_GKE_TEST_CLUSTER_OPERATOR }}
        with:
          entrypoint: make
          args: images.all manifests.generate
      - name: Store OCI image tarballs and generated manifests
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            image-*.oci
            image-*.tag
            config/operator/operator-test.yaml
  test-controllers:
    needs: build-image
    strategy:
      matrix:
        kube_version: [1.17, 1.18]
    name: Create kind clusters and test new image
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Fetch OCI image tarvalls and generated manifests
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./
      - name: Create Kubernetes cluster (${{ matrix.kube_version }})
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        with:
          entrypoint: kind
          args: create cluster --config /etc/kind/${{ matrix.kube_version }}/standard-github-actions-cluster.yaml --kubeconfig /github/workspace/kubeconfig
      - name: Load OCI image into the cluster
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        with:
          entrypoint: kind
          args: load image-archive image-gke-test-cluster-operator.oci
      - name: Set kubeconfig context
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        env:
          KUBECONFIG: "/github/workspace/kubeconfig"
        with:
          entrypoint: kubectl
          args: config use-context kind-kind
      - name: Deploy Cilium and Config Connector CRDs
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        env:
          KUBECONFIG: "/github/workspace/kubeconfig"
        with:
          entrypoint: kubectl
          args: apply --filename config/test-deps
      - name: Wait for nodes to become ready
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        env:
          KUBECONFIG: "/github/workspace/kubeconfig"
        with:
          entrypoint: kubectl
          args: wait nodes --for=condition=Ready --all --timeout=5m
      - name: Deploy Cert Manager
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        env:
          KUBECONFIG: "/github/workspace/kubeconfig"
        with:
          entrypoint: kubectl
          args: apply --filename config/cert-manager/cert-manager.yaml
      - name: Run controller tests
        uses: docker://docker.io/cilium/kube-test:6f40eb5b6bdc4c86d3fa2456d73d93a1a5814481
        env:
          KUBECONFIG: "/github/workspace/kubeconfig"
        timeout-minutes: 10
        with:
          entrypoint: make
          args: test.controllers
  push-images:
    if: github.repository == 'isovalent/gke-test-cluster-operator' && github.ref == 'refs/heads/main'
    needs: test-controllers
    name: Build all images and push to the registry
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for imagine to detect -dev suffix
      - uses: docker://quay.io/cilium/image-maker:68cf0628c7a77124319cb8c33434b8cdb42a3865
        name: Build and push all images
        env:
          DOCKER_HUB_PUBLIC_ACCESS_ONLY: "true"
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME_GKE_TEST_CLUSTER_OPERATOR }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD_GKE_TEST_CLUSTER_OPERATOR }}
        with:
          entrypoint: make
          args: images.all PUSH=true
